apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: { app: rag-api }
  template:
    metadata:
      labels: { app: rag-api }
    spec:
      containers:
      - name: rag-api
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - containerPort: 8080
        env:
        {{- range $k, $v in .Values.env }}
          - name: {{ $k }}
            value: "{{ $v }}"
        {{- end }}
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop: ["ALL"]
        resources:
{{ toYaml .Values.resources | indent 10 }}
