apiVersion: v1
kind: Namespace
metadata:
  name: ingest
---
apiVersion: v1
kind: Namespace
metadata:
  name: search
---
apiVersion: v1
kind: Namespace
metadata:
  name: vector
---
apiVersion: v1
kind: Namespace
metadata:
  name: llm
---
apiVersion: v1
kind: Namespace
metadata:
  name: api
