# Example values for your internal OpenSearch mirror chart
singleNode: true
replicas: 1
persistence:
  enabled: true
  size: 100Gi
resources:
  requests:
    cpu: "2"
    memory: "8Gi"
  limits:
    cpu: "4"
    memory: "16Gi"
opensearchJavaOpts: "-Xms4g -Xmx4g"
securityConfig:
  enabled: true
  admin:
    existingSecret: opensearch-admin-secret
